set_project("lc-finder")
set_version("0.3.0")
set_warnings("all")
add_rules("mode.debug", "mode.release")
add_configfiles("include/config.h.in", {prefix = "LCFINDER"})
add_cfuncs("3rdparty", "sqlite3", "sqlite3.h", "sqlite3_open")
add_linkdirs("vendor/lib")
add_includedirs("include", "vendor/include")
add_links("LCUI", "LCDesign", "yaml", "darknet")
add_rpathdirs("./lib")

target("lc-finder")
    set_targetdir("app/")
    set_kind("binary")
    add_files("src/**.c")

target("test")
    set_targetdir("app/")
    set_kind("binary")
    add_files("test/test.c", "src/lib/file_storage.c", "src/lib/file_service.c", "src/lib/common.c", "src/lib/sha1.c")
